openapi: 3.0.0
info:
  title: User service API
  description: API description in Markdown.
  version: 1.0.0

paths:

components:
  securitySchemes:

  ######################################################################################################################
  ##                                             Security components                                                  ##
  ######################################################################################################################

    JWTAcessToken:
      description: Authentication with JWT stored in cookies
      type: apiKey
      in: cookie
      name: access_token_cookie
    JWTRefreshToken:
      description: JWT stored in cookies to refresh an acess token
      type: apiKey
      in: cookie
      name: refresh_token_cookie
    CSRFAcessToken:
      description: CSRF acess token
      type: apiKey
      in: header
      name: X-CSRF-TOKEN
    CSRFRefreshToken:
      description: CSRF refresh token for "remember me" functionality
      type: apiKey
      in: header
      name: X-CSRF-TOKEN
  schemas:

  ######################################################################################################################
  ##                                             Error handling                                                       ##
  ######################################################################################################################

    errorResponse:
      title: 'Error response'
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            title: 'Error value'
            required:
              - status
              - title
            properties:
              class:
                type: string
              status:
                type: integer
              title:
                type: string

  ######################################################################################################################
  ##                                             Common data types                                                    ##
  ######################################################################################################################

    typeEmail:
      type: string
      pattern: '^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$'
      maxLength: 64
      example: 'example@example.org'
    typePhone:
      type: string
      pattern: '(?:(?:\+?1\s*(?:[.-]\s*)?)?(?:(\s*([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]‌​)\s*)|([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]))\s*(?:[.-]\s*)?)([2-9]1[02-9]‌​|[2-9][02-9]1|[2-9][02-9]{2})\s*(?:[.-]\s*)?([0-9]{2})\s*(?:[.-]\s*)?([0-9]{2})(?:\s*(?:#|x\.?|ext\.?|extension)\s*(\d+))?$'
      maxLength: 32
      example: 8-800-555-35-35
    typePassword:
      type: string
      format: password
      maxLength: 128
      example: qwertyA*1
    typeUsername:
      type: string
      # Must be equal to or larger than email max length
      maxLength: 64
    typeCommonName:
      type: string
      maxLength: 32
    typeDate:
      type: string
      format: date
    typeGrade:
      type: integer
      minimum: 1
      maximum: 5
      example: 1
    typeRememberMe:
      type: boolean
    typeCSRFToken:
      type: string
    typeIdentifier:
      type: integer
    typeGroupName:
      type: string
      maxLength: 32
    typeUserRole:
      title: 'User role'
      type: string
      enum: [ 'Admin', 'Creator', 'Participant', 'System' ]
    typeUserType:
      title: 'All user type'
      type: string
      enum: [ 'PreUniversity', 'Enrollee', 'School', 'University', 'Internal', 'PreRegister' ]