openapi: 3.0.0
info:
  title: Student responses service API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000/contest/responses/general
  - url: http://127.0.0.1:5000

paths:
  ######################################################################################################################
  ##                                             Path definition                                                      ##
  ######################################################################################################################

  # Appeal

  /contest/{contest_id}/appeal/{appeal_id}:
    get:
      summary: Get appeal info
      security:
        - cookieJWTAuth: [ ]
      parameters:
        - in: path
          description: Id of the contest
          name: contest_id
          required: true
          schema:
            type: integer
        - in: path
          description: Id of the appeal
          name: appeal_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commonAppealInfo'
        '404':
          description: Appeal or contest not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

    # User answer

  /contest/{contest_id}/user/{user_id}/response:
    get:
      summary: Get all user answers for the contest
      security:
        - cookieJWTAuth: [ ]
      parameters:
        - in: path
          description: Id of the contest
          name: contest_id
          required: true
          schema:
            type: integer
        - in: path
          description: Id of the user
          name: user_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userContestAllAnswer'
        '403':
          description: Not enough rights for current user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '404':
          description: User or contest not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /contest/{contest_id}/answer/{answer_id}:
    get:
      summary: Get user's answer by id
      security:
        - cookieJWTAuth: [ ]
      parameters:
        - in: path
          description: Id of the contest
          name: contest_id
          required: true
          schema:
            type: integer
        - in: path
          description: Id of the answer
          name: answer_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userContestAnswer'
        '403':
          description: Not enough rights for current user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '404':
          description: User or contest not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'



components:
  securitySchemes:

  ######################################################################################################################
  ##                                             Security components                                                  ##
  ######################################################################################################################

    cookieJWTAuth:
      description: Authentication with JWT stored in cookies
      type: apiKey
      in: cookie
      name: access_token_cookie
    CSRFToken:
      description: CSRF token
      type: apiKey
      in: header
      name: X-CSRF-TOKEN
  schemas:

  ######################################################################################################################
  ##                                             Error handling                                                       ##
  ######################################################################################################################

    errorResponse:
      title: 'Error response'
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            title: 'Error value'
            required:
              - status
              - title
            properties:
              class:
                type: string
              status:
                type: integer
              title:
                type: string

  ######################################################################################################################
  ##                                             Common data types                                                    ##
  ######################################################################################################################

    typeCommonName:
      type: string
      maxLength: 32
    typeIdentifier:
      type: integer
    typeMessage:
      type: string
      maxLength: 4096
    typeNullableMessage:
      type: string
      maxLength: 4096
      nullable: true
    typeUserAnswer:
      type: string
      # format: binary     # TODO FILE
    typeFiletype:
      type: string
      enum: [ "txt", "pdf", "jpg", "doc", "docx", "png", "gif", "odt" ]

  ######################################################################################################################
  ##                                             Path schemas                                                         ##
  ######################################################################################################################

    commonAppealInfo:
      title: "Common appeal info"
      required:
        - appeal_id
        - status_id
        - appeal_status
        - appeal_message
        - appeal_response
      properties:
        appeal_id:
          $ref: '#/components/schemas/typeIdentifier'
        status_id:
          $ref: '#/components/schemas/typeIdentifier'
        appeal_status:
          $ref: '#/components/schemas/typeCommonName'
        appeal_message:
          $ref: '#/components/schemas/typeMessage'
        appeal_response:
          $ref: '#/components/schemas/typeNullableMessage'

    userContestAllAnswer:
      title: "ALl user's answer for the contest"
      required:
        - user_id
        - work_id
        - contest_id
      properties:
        user_id:
          $ref: '#/components/schemas/typeIdentifier'
        work_id:
          $ref: '#/components/schemas/typeIdentifier'
        contest_id:
          $ref: '#/components/schemas/typeIdentifier'
        user_answers:
          type: array
          items:
            $ref: '#/components/schemas/typeUserAnswerForList'

    typeUserAnswerForList:
      title: "User answer"
      required:
        - task_id
        - answer_id
      properties:
        task_id:
          $ref: '#/components/schemas/typeIdentifier'
        answer_id:
          $ref: '#/components/schemas/typeIdentifier'

    userContestAnswer:
      title: "User's contest answer"
      required:
        - user_answer
        - filetype
      properties:
        user_answer:
          $ref: '#/components/schemas/typeUserAnswer'
        filetype:
          $ref: '#/components/schemas/typeFiletype'
