openapi: 3.0.0
info:
  title: Tasks service API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000/contest/tasks/admin
  - url: http://127.0.0.1:5000

paths:
  ######################################################################################################################
  ##                                             Path definition                                                      ##
  ######################################################################################################################

  # Olympiad type

  /olympiad_type/create:
    post:
      summary: add olympiad type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/olympiadType'
      security:
        - JWTAcessToken: [ ]
        - CSRFAcessToken: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/olympiadTypeId'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '409':
          description: Already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /olympiad_type/{id_olympiad_type}/remove:
    post:
      summary: remove olympiad type
      parameters:
        - in: path
          description: Id of the olympiad type
          name: id_olympiad_type
          required: true
          schema:
            type: integer
      security:
        - JWTAcessToken: [ ]
        - CSRFAcessToken: [ ]
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '404':
          description: Olympiad type not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'


  # Users

  /contest/{id_contest}/add_user:
    post:
      summary: Add user to contest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateUserInContest'
      parameters:
        - in: path
          description: Id of the contest
          name: id_contest
          required: true
          schema:
            type: integer
      security:
        - JWTAcessToken: [ ]
        - CSRFAcessToken: [ ]
      responses:
        '200':
          description: OK
        '404':
          description: User or group not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '409':
          description: User is already exists or no variants for this contest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '400':
          description: Request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

  /contest/{id_contest}/remove_user:
    post:
      summary: Remove user from contest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateUserInContest'
      parameters:
        - in: path
          description: Id of the contest
          name: id_contest
          required: true
          schema:
            type: integer
      security:
        - JWTAcessToken: [ ]
        - CSRFAcessToken: [ ]
      responses:
        '200':
          description: OK
        '404':
          description: User or group not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

  /contest/{id_contest}/user/all:
    get:
      summary: list of user in contest
      parameters:
        - in: path
          description: Id of the contest
          name: id_contest
          required: true
          schema:
            type: integer
      security:
        - JWTAcessToken: [ ]
        - CSRFAcessToken: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/usersInContest'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

  /contest/{id_contest}/user/{id_user}/certificate:
    get:
      summary: certificate of user in contest
      parameters:
        - in: path
          description: Id of the contest
          name: id_contest
          required: true
          schema:
            type: integer
        - in: path
          description: Id of the user
          name: id_user
          required: true
          schema:
            type: integer
      security:
        - JWTAcessToken: [ ]
        - CSRFAcessToken: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userCertificate'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'



  ######################################################################################################################
  ##                                             Path schemas                                                         ##
  ######################################################################################################################

components:
  securitySchemes:

  ######################################################################################################################
  ##                                             Security components                                                  ##
  ######################################################################################################################

    JWTAcessToken:
      description: Authentication with JWT stored in cookies
      type: apiKey
      in: cookie
      name: access_token_cookie
    JWTRefreshToken:
      description: JWT stored in cookies to refresh an acess token
      type: apiKey
      in: cookie
      name: refresh_token_cookie
    CSRFAcessToken:
      description: CSRF acess token
      type: apiKey
      in: header
      name: X-CSRF-TOKEN
    CSRFRefreshToken:
      description: CSRF refresh token for "remember me" functionality
      type: apiKey
      in: header
      name: X-CSRF-TOKEN
  schemas:

  ######################################################################################################################
  ##                                             Error handling                                                       ##
  ######################################################################################################################

    errorResponse:
      title: 'Error response'
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            title: 'Error value'
            required:
              - status
              - title
            properties:
              class:
                type: string
              status:
                type: integer
              title:
                type: string

  ######################################################################################################################
  ##                                             Common data types                                                    ##
  ######################################################################################################################

    typeOlympiadName:
      type: string
      maxLength: 256
    typeOlympiadType:
      type: string
      maxLength: 256
    typeOlympiadLocation:
      type: string
      maxLength: 256
    typeOlympiadText:
      type: string
      maxLength: 1024
    typeDate:
      type: string
      format: date
    typeFile:
      type: string
      format: binary
      nullable: true
    typeVisibility:
      type: boolean
    typeCorrectness:
      type: boolean
    typeMultipleAnswer:
      type: string
      maxLength: 256
    typeIdentifier:
      type: integer
    typePartNum:
      type: integer
      minimum: 0
      maximum: 1000
    typeCondition:
      type: number
      format: float
      minimum: 0.0
      maximum: 100.0
      example:
        5.5
    typeRangeAnswer:
      type: number
      format: float
      maxLength: 128
      example:
        5.5
    typeTargetClass:
      title: 'All target classes types'
      type: string
      enum: [ "5", "6", "7", "8", "9", "10", "11", "student" ]
    typeSubject:
      title: 'All subject types'
      type: string
      enum: [ "Math", "Physics", "Informatics" ]
    typeParticipant:
      title: 'All subject types'
      type: string
      enum: [ "Participant", "Laureate", "Winner" ]
    typeStageCondition:
      title: 'All stage condition types'
      type: string
      enum: [ "No", "And", "Or" ]
      nullable: true
    typeComposite:
      title: 'All contest types'
      type: string
      enum: [ "SimpleContest", "CompositeContest" ]

  ######################################################################################################################
  ##                                             Path schemas                                                         ##
  ######################################################################################################################

    # /contest/{id_contest}/user/all

    usersInContest:
      title: Get users in contest
      description: Request to get users in contest
      properties:
        user_list:
          type: array
          items:
            type: object
            properties:
              user_id:
                $ref: '#/components/schemas/typeIdentifier'
              variant_id:
                $ref: '#/components/schemas/typeIdentifier'
              user_status:
                $ref: '#/components/schemas/typeParticipant'

    # /contest/{id_contest}/add_user
    # /contest/{id_contest}/remove_user

    updateUserInContest:
      title: Add or remove user to contest or stage
      description: Request to add or remove user user to contest or stage
      required:
        - users_id
      properties:
        users_id:
          type: array
          items:
            $ref: '#/components/schemas/typeIdentifier'

    # /contest/{id_contest}/user/{id_user}/certificate

    userCertificate:
      title: Get certificate of the user
      description: Request to get certificate of the user
      required:
        - certificate
      properties:
        certificate:
          $ref: '#/components/schemas/typeFile'

    # /olympiad_type/create

    olympiadType:
      title: 'Add or remove olympiad type'
      description: 'Request to add or remove olympiad type'
      required:
        - olympiad_type
      properties:
        olympiad_type:
          $ref: '#/components/schemas/typeOlympiadType'

    # /olympiad_type/{id_olympiad_type}/remove

    olympiadTypeId:
      title: Get olympiad type id
      description: Request to get olympiad type id
      required:
        - olympiad_type_id
      properties:
        olympiad_type_id:
          $ref: '#/components/schemas/typeIdentifier'
