openapi: 3.0.0
info:
  title: User service API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
  - url: http://127.0.0.1:5000/user/auth

paths:
  ######################################################################################################################
  ##                                             Path definition                                                      ##
  ######################################################################################################################

  /login:
    post:
      summary: Authenticate a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestLogin'
      security: []
      responses:
        '200':
          description: OK
          headers:
            Set-Cookie:
              schema:
                description: Set both access_token_cookie and refresh_token_cookie
                type: string
                example: access_token_cookie=eyJ0eXAi...; Path=/; HttpOnly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseLogin'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '401':
          description: Wrong credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /refresh:
    post:
      summary: Refresh JWT token for current user
      security:
        - JWTRefreshToken: [ ]
        - CSRFRefreshToken: [ ]
      responses:
        '200':
          description: OK
          headers:
            Set-Cookie:
              schema:
                description: Set both access_token_cookie and refresh_token_cookie
                type: string
                example: access_token_cookie=eyJ0eXAi...; Path=/; HttpOnly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseRefresh'
  /logout:
    post:
      summary: Logout current user
      security:
        - JWTAcessToken: []
        - CSRFAcessToken: [] #framework limitations
      responses:
        '200':
          description: OK
          headers:
            Set-Cookie:
              schema:
                description: Set both access_token_cookie and refresh_token_cookie
                type: string
                example: access_token_cookie=deleted; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT

components:
  securitySchemes:

  ######################################################################################################################
  ##                                             Security components                                                  ##
  ######################################################################################################################
    
    JWTAcessToken:
      description: Authentication with JWT stored in cookies
      type: apiKey
      in: cookie
      name: access_token_cookie
    JWTRefreshToken:
      description: JWT stored in cookies to refresh an acess token
      type: apiKey
      in: cookie
      name: refresh_token_cookie
    CSRFAcessToken:
      description: CSRF acess token
      type: apiKey
      in: header
      name: X-CSRF-TOKEN
    CSRFRefreshToken:
      description: CSRF refresh token for "remember me" functionality
      type: apiKey
      in: header
      name: X-CSRF-TOKEN
  schemas:

  ######################################################################################################################
  ##                                             Error handling                                                       ##
  ######################################################################################################################

    errorResponse:
      title: 'Error response'
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            title: 'Error value'
            required:
              - status
              - title
            properties:
              class:
                type: string
              status:
                type: integer
              title:
                type: string

  ######################################################################################################################
  ##                                             Common data types                                                    ##
  ######################################################################################################################

    typePassword:
      type: string
      format: password
      maxLength: 128
      example: qwertyA*1
    typeUsername:
      type: string
      # Must be equal to or larger than email max length
      maxLength: 64
    typeRememberMe:
      type: boolean
    typeCSRFToken:
      type: string

  ######################################################################################################################
  ##                                             Composite data types                                                 ##
  ######################################################################################################################

    # Authorization data

    typeAuthCredentials:
      title: 'Authentication info'
      required:
        - username
        - password
      properties:
        username:
          $ref: '#/components/schemas/typeUsername'
        password:
          $ref: '#/components/schemas/typePassword'
    typeCSRFPair:
      required:
        - csrf_access_token
        - csrf_refresh_token
      properties:
        csrf_access_token:
          $ref: '#/components/schemas/typeCSRFToken'
        csrf_refresh_token:
          $ref: '#/components/schemas/typeCSRFToken'



  ######################################################################################################################
  ##                                             Path schemas                                                         ##
  ######################################################################################################################

    # /login

    requestLogin:
      title: 'Authentication request info'
      required:
        - auth_credentials
        - remember_me
      properties:
        auth_credentials:
          $ref: '#/components/schemas/typeAuthCredentials'
        remember_me:
          $ref: '#/components/schemas/typeRememberMe'
    responseLogin:
      $ref: '#/components/schemas/typeCSRFPair'

    # /refresh

    responseRefresh:
      $ref: '#/components/schemas/typeCSRFPair'

    # /logout