stages:
  - build
  - deploy



build-frontend:
  image: node:lts-slim
  stage: build
  before_script:
    - 'yarn --cwd frontend install'
  script:
    - 'yarn --cwd frontend run build'
  artifacts:
    paths:
      - frontend/dist
  when: manual