stages:
  - build
  - deploy


build-frontend:
  image: node:lts-slim
  stage: build
  script:
    - 'yarn --cwd frontend install'
    - 'yarn --cwd frontend build'
  artifacts:
    paths:
      - frontend/dist
  when: manual

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r frontend/dist .public
    - mv .public public
  artifacts:
    paths:
      - public
  when: manual