stages:
  - build

.job_template: &build
  image: node:lts-slim
  stage: build
  before_script:
    - 'yarn --cwd frontend install'
  script:
    - 'yarn --cwd frontend run build'
  artifacts:
    paths:
      - frontend/dist

build-frontend-prod:
  <<: *build
  only:
    - master
    - frontend
    - backend
    - tags

build-frontend-dev:
  <<: *build
  when: manual
  except:
    - master
    - frontend
    - backend
    - tags