/**
 * aggregate_contest_responses
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AnswerWithoutMark { 
    readonly answer_id?: number;
    answer_type?: AnswerWithoutMark.AnswerTypeEnum;
    readonly task_id?: number | null;
}
export namespace AnswerWithoutMark {
    export type AnswerTypeEnum = 'PlainAnswerText' | 'PlainAnswerFile' | 'RangeAnswer' | 'MultipleChoiceAnswer' | 'BaseAnswer';
    export const AnswerTypeEnum = {
        PlainAnswerText: 'PlainAnswerText' as AnswerTypeEnum,
        PlainAnswerFile: 'PlainAnswerFile' as AnswerTypeEnum,
        RangeAnswer: 'RangeAnswer' as AnswerTypeEnum,
        MultipleChoiceAnswer: 'MultipleChoiceAnswer' as AnswerTypeEnum,
        BaseAnswer: 'BaseAnswer' as AnswerTypeEnum
    };
}


