/**
 * aggregate_contest_responses
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubjectEnum } from '@api/shared/model'


export interface ContestInfo {
    academic_year: number;
    composite_type: ContestInfo.CompositeTypeEnum;
    readonly contest_id: number;
    readonly name: string;
    subject?: SubjectEnum;
}
export namespace ContestInfo {
    export type CompositeTypeEnum = 'SimpleContest';
    export const CompositeTypeEnum = {
        SimpleContest: 'SimpleContest' as CompositeTypeEnum
    };
}


