/**
 * aggregate_contest_responses
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContestInfo { 
    readonly contest_id: number;
    end_year: number;
    readonly name: string;
    start_year: number;
    subject?: ContestInfo.SubjectEnum;
}
export namespace ContestInfo {
    export type SubjectEnum = 'Math' | 'Physics' | 'Informatics' | 'Natural Sciences' | 'Engineering Sciences' | 'Other';
    export const SubjectEnum = {
        Math: 'Math' as SubjectEnum,
        Physics: 'Physics' as SubjectEnum,
        Informatics: 'Informatics' as SubjectEnum,
        NaturalSciences: 'Natural Sciences' as SubjectEnum,
        EngineeringSciences: 'Engineering Sciences' as SubjectEnum,
        Other: 'Other' as SubjectEnum
    };
}


