/**
 * aggregate_contest_responses
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PlainAnswerFile { 
    filetype?: PlainAnswerFile.FiletypeEnum;
}
export namespace PlainAnswerFile {
    export type FiletypeEnum = 'txt' | 'pdf' | 'jpg' | 'doc' | 'docx' | 'png' | 'gif' | 'odt';
    export const FiletypeEnum = {
        Txt: 'txt' as FiletypeEnum,
        Pdf: 'pdf' as FiletypeEnum,
        Jpg: 'jpg' as FiletypeEnum,
        Doc: 'doc' as FiletypeEnum,
        Docx: 'docx' as FiletypeEnum,
        Png: 'png' as FiletypeEnum,
        Gif: 'gif' as FiletypeEnum,
        Odt: 'odt' as FiletypeEnum
    };
}


