/**
 * aggregate_contest_responses
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskForUserResponseResults { 
    task_id: number;
    task_points: number;
    task_type?: TaskForUserResponseResults.TaskTypeEnum;
}
export namespace TaskForUserResponseResults {
    export type TaskTypeEnum = 'PlainTask' | 'RangeTask' | 'MultipleChoiceTask' | 'BaseTask';
    export const TaskTypeEnum = {
        PlainTask: 'PlainTask' as TaskTypeEnum,
        RangeTask: 'RangeTask' as TaskTypeEnum,
        MultipleChoiceTask: 'MultipleChoiceTask' as TaskTypeEnum,
        BaseTask: 'BaseTask' as TaskTypeEnum
    };
}


