/**
 * aggregate_contest_responses
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContestInfo } from './contestInfo';


export interface UserResultsForContestResponse { 
    contest_info: ContestInfo;
    mark: number;
    status: UserResultsForContestResponse.StatusEnum;
    user_status: UserResultsForContestResponse.UserStatusEnum;
}
export namespace UserResultsForContestResponse {
    export type StatusEnum = 'InProgress' | 'NotChecked' | 'Accepted' | 'Rejected' | 'Appeal' | 'Correction' | 'NoResults';
    export const StatusEnum = {
        InProgress: 'InProgress' as StatusEnum,
        NotChecked: 'NotChecked' as StatusEnum,
        Accepted: 'Accepted' as StatusEnum,
        Rejected: 'Rejected' as StatusEnum,
        Appeal: 'Appeal' as StatusEnum,
        Correction: 'Correction' as StatusEnum,
        NoResults: 'NoResults' as StatusEnum
    };
    export type UserStatusEnum = 'Winner 1' | 'Winner 2' | 'Winner 3' | 'Diploma 1' | 'Diploma 2' | 'Diploma 3' | 'Participant';
    export const UserStatusEnum = {
        Winner1: 'Winner 1' as UserStatusEnum,
        Winner2: 'Winner 2' as UserStatusEnum,
        Winner3: 'Winner 3' as UserStatusEnum,
        Diploma1: 'Diploma 1' as UserStatusEnum,
        Diploma2: 'Diploma 2' as UserStatusEnum,
        Diploma3: 'Diploma 3' as UserStatusEnum,
        Participant: 'Participant' as UserStatusEnum
    };
}


