/**
 * aggregate_contest_tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TargetClass } from './targetClass';


export interface BaseOlympiadResponseTaskCreator { 
    readonly base_contest_id?: number;
    description?: string;
    diploma_1_condition?: number;
    diploma_2_condition?: number;
    diploma_3_condition?: number;
    level?: BaseOlympiadResponseTaskCreator.LevelEnum;
    name?: string;
    olympiad_type_id?: number;
    rules?: string;
    subject?: BaseOlympiadResponseTaskCreator.SubjectEnum;
    target_classes?: Array<TargetClass>;
    winner_1_condition?: number;
    winner_2_condition?: number;
    winner_3_condition?: number;
}
export namespace BaseOlympiadResponseTaskCreator {
    export type LevelEnum = '1' | '2' | '3' | 'No level';
    export const LevelEnum = {
        _1: '1' as LevelEnum,
        _2: '2' as LevelEnum,
        _3: '3' as LevelEnum,
        NoLevel: 'No level' as LevelEnum
    };
    export type SubjectEnum = 'Math' | 'Physics' | 'Informatics' | 'Natural Sciences' | 'Engineering Sciences' | 'Other';
    export const SubjectEnum = {
        Math: 'Math' as SubjectEnum,
        Physics: 'Physics' as SubjectEnum,
        Informatics: 'Informatics' as SubjectEnum,
        NaturalSciences: 'Natural Sciences' as SubjectEnum,
        EngineeringSciences: 'Engineering Sciences' as SubjectEnum,
        Other: 'Other' as SubjectEnum
    };
}


