/**
 * aggregate_contest_tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BaseContest { 
    readonly base_contest_id?: number;
    description: string;
    laureate_condition: number;
    name: string;
    olympiad_type_id: number;
    rules: string;
    subject: BaseContest.SubjectEnum;
    target_classes: Array<BaseContest.TargetClassesEnum>;
    winning_condition: number;
}
export namespace BaseContest {
    export type SubjectEnum = 'Math' | 'Physics' | 'Informatics';
    export const SubjectEnum = {
        Math: 'Math' as SubjectEnum,
        Physics: 'Physics' as SubjectEnum,
        Informatics: 'Informatics' as SubjectEnum
    };
    export type TargetClassesEnum = '5' | '6' | '7' | '8' | '9' | '10' | '11' | 'student';
    export const TargetClassesEnum = {
        _5: '5' as TargetClassesEnum,
        _6: '6' as TargetClassesEnum,
        _7: '7' as TargetClassesEnum,
        _8: '8' as TargetClassesEnum,
        _9: '9' as TargetClassesEnum,
        _10: '10' as TargetClassesEnum,
        _11: '11' as TargetClassesEnum,
        Student: 'student' as TargetClassesEnum
    };
}


