/**
 * aggregate_contest_tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CompositeContest { 
    readonly contest_id: number;
    holding_type: CompositeContest.HoldingTypeEnum;
    visibility: boolean;
}
export namespace CompositeContest {
    export type HoldingTypeEnum = 'OfflineContest' | 'OnLineContest';
    export const HoldingTypeEnum = {
        OfflineContest: 'OfflineContest' as HoldingTypeEnum,
        OnLineContest: 'OnLineContest' as HoldingTypeEnum
    };
}


