/**
 * aggregate_contest_tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ListElemContestGroupRestrictionAdmin { 
    group_name: string;
    restriction: ListElemContestGroupRestrictionAdmin.RestrictionEnum;
}
export namespace ListElemContestGroupRestrictionAdmin {
    export type RestrictionEnum = 'ViewMarkAndUserStatus' | 'ViewResponse' | 'EditMark' | 'EditUserStatus';
    export const RestrictionEnum = {
        ViewMarkAndUserStatus: 'ViewMarkAndUserStatus' as RestrictionEnum,
        ViewResponse: 'ViewResponse' as RestrictionEnum,
        EditMark: 'EditMark' as RestrictionEnum,
        EditUserStatus: 'EditUserStatus' as RestrictionEnum
    };
}


