/**
 * aggregate_contest_tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PlainTask { 
    answer_type?: PlainTask.AnswerTypeEnum;
    num_of_task: number;
    recommended_answer: string;
    show_answer_after_contest?: boolean | null;
    readonly task_id: number;
    task_points?: number | null;
}
export namespace PlainTask {
    export type AnswerTypeEnum = 'File' | 'Text';
    export const AnswerTypeEnum = {
        File: 'File' as AnswerTypeEnum,
        Text: 'Text' as AnswerTypeEnum
    };
}


