/**
 * aggregate_contest_tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateBaseOlympiadRequestTaskEditor { 
    description?: string;
    diploma_1_condition?: number;
    diploma_2_condition?: number;
    diploma_3_condition?: number;
    name?: string;
    olympiad_type_id?: number;
    rules?: string;
    subject?: UpdateBaseOlympiadRequestTaskEditor.SubjectEnum;
    winner_1_condition?: number;
    winner_2_condition?: number;
    winner_3_condition?: number;
}
export namespace UpdateBaseOlympiadRequestTaskEditor {
    export type SubjectEnum = 'Math' | 'Physics' | 'Informatics';
    export const SubjectEnum = {
        Math: 'Math' as SubjectEnum,
        Physics: 'Physics' as SubjectEnum,
        Informatics: 'Informatics' as SubjectEnum
    };
}


