/**
 * aggregate_contest_tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubjectEnum } from '@api/shared/model'


export interface UpdateBaseOlympiadRequestTaskEditor {
    description?: string;
    diploma_1_condition?: number;
    diploma_2_condition?: number;
    diploma_3_condition?: number;
    level?: UpdateBaseOlympiadRequestTaskEditor.LevelEnum;
    name?: string;
    olympiad_type_id?: number;
    rules?: string;
    subject?: SubjectEnum;
    winner_1_condition?: number;
    winner_2_condition?: number;
    winner_3_condition?: number;
}
export namespace UpdateBaseOlympiadRequestTaskEditor {
    export type LevelEnum = '1' | '2' | '3' | 'No level';
    export const LevelEnum = {
        _1: '1' as LevelEnum,
        _2: '2' as LevelEnum,
        _3: '3' as LevelEnum,
        NoLevel: 'No level' as LevelEnum
    };
}


