/**
 * aggregate_contest_tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserInContest { 
    proctoring_login?: string | null;
    proctoring_password?: string | null;
    show_results_to_user?: boolean | null;
    supervisor?: string | null;
    readonly user_id: number;
    user_status: UserInContest.UserStatusEnum;
    readonly variant_id?: number | null;
}
export namespace UserInContest {
    export type UserStatusEnum = 'Winner 1' | 'Winner 2' | 'Winner 3' | 'Diploma 1' | 'Diploma 2' | 'Diploma 3' | 'Participant';
    export const UserStatusEnum = {
        Winner1: 'Winner 1' as UserStatusEnum,
        Winner2: 'Winner 2' as UserStatusEnum,
        Winner3: 'Winner 3' as UserStatusEnum,
        Diploma1: 'Diploma 1' as UserStatusEnum,
        Diploma2: 'Diploma 2' as UserStatusEnum,
        Diploma3: 'Diploma 3' as UserStatusEnum,
        Participant: 'Participant' as UserStatusEnum
    };
}


