openapi: 3.0.0
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:5000/subservice1/module1'
  - url: 'http://127.0.0.1:5000/module1'
  - url: 'http://127.0.0.1:5000'
paths:
  /add:
    post:
      responses:
        '200':
          description: OK
