openapi: 3.0.0
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:5000/subservice1/module2'
  - url: 'http://127.0.0.1:5000/module2'
  - url: 'http://127.0.0.1:5000'
paths:
  /get/{user_id}:
    get:
      parameters:
        - in: path
          description: Id of the user
          name: user_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                required:
                  - id
                  - name
                properties:
                  id:
                    type: integer
                  name:
                    type: string
        '404':
          description: Not found


