openapi: 3.0.0
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:5000/subservice2'
  - url: 'http://127.0.0.1:5000'
paths:
  /hello:
    post:
      requestBody:
        content:
          application/json:
            schema:
              required:
                - now
              properties:
                now:
                  type: string
                  format: 'date-time'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                required:
                  - msg
                properties:
                  msg:
                    type: string
