class DefaultConfiguration:
    SQLALCHEMY_DATABASE_URI = 'sqlite:///database.sqlite'
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    ORGMEPHI_USERNAME_MAXLEN = 20
    ORGMEPHI_API_PATH = 'api.yaml'
    ORGMEPHI_NAME_MAXLEN = 20
    ORGMEPHI_PHONE_MAXLEN = 12
    ORGMEPHI_UNIVERSITY_MAXLEN = 50
    ORGMEPHI_UNIVERSITY_FILE = 'universities.txt'
    ORGMEPHI_LOCATION_MAXLEN = 50
    ORGMEPHI_COUNTRY_FILE = 'countries.txt'
    ORGMEPHI_PASSWORD_HASH = 'pbkdf2_sha256'
    ORGMEPHI_PASSWORD_LENGTH = 8
    ORGMEPHI_PASSWORD_UPPERCASE = 1
    ORGMEPHI_PASSWORD_NUMBERS = 1
    ORGMEPHI_PASSWORD_SPECIAL = 1
    ORGMEPHI_PASSWORD_NONLETTERS = 0
