/**
 * User service API
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TypeRegistrationCredentials } from './typeRegistrationCredentials';
import { TypeRegistrationPersonalInfo } from './typeRegistrationPersonalInfo';
import { TypeRegistrationStudentInfo } from './typeRegistrationStudentInfo';
import { TypeUserTypeUniversity } from './typeUserTypeUniversity';

export interface RequestRegistrationUniversity { 
    authInfo: TypeRegistrationCredentials;
    personalInfo: TypeRegistrationPersonalInfo;
    registerType: TypeUserTypeUniversity;
    studentInfo: TypeRegistrationStudentInfo;
}