/**
 * User service API
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type RoleType = 'Admin' | 'Creator' | 'Participant' | 'System';

export const RoleType = {
    Admin: 'Admin' as RoleType,
    Creator: 'Creator' as RoleType,
    Participant: 'Participant' as RoleType,
    System: 'System' as RoleType
}