/**
 * User service API
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Set fields that should be changed
 */
export interface StudentInfoUpdate
{
    phoneNumber?: string;
    university?: string;
    grade?: number;
    universityCountry?: string;
    citizenship?: string;
    region?: string;
    city?: string;
}