/**
 * User service API
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TypeCommonName } from './typeCommonName';
import { TypeGrade } from './typeGrade';
import { TypePhone } from './typePhone';

export interface TypeRegistrationStudentInfo { 
    phoneNumber: TypePhone;
    university: TypeCommonName;
    grade: TypeGrade;
    universityCountry: TypeCommonName;
    citizenship: TypeCommonName;
    region: TypeCommonName;
    city: TypeCommonName;
}