/**
 * User service API
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TypeCommonName } from './typeCommonName';
import { TypeDate } from './typeDate';
import { TypeEmail } from './typeEmail';

export interface TypePersonalInfo { 
    email?: TypeEmail;
    firstName?: TypeCommonName;
    secondName?: TypeCommonName;
    middleName?: TypeCommonName;
    dateOfBirth?: TypeDate;
}