/**
 * User service API
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TypeUserTypeSchool = 'PreUniversity' | 'Enrollee' | 'School';

export const TypeUserTypeSchool = {
    PreUniversity: 'PreUniversity' as TypeUserTypeSchool,
    Enrollee: 'Enrollee' as TypeUserTypeSchool,
    School: 'School' as TypeUserTypeSchool
};