/**
 * User service API
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TypeCommonName } from './typeCommonName';
import { TypeIdentifier } from './typeIdentifier';
import { TypeUserRole } from './typeUserRole';
import { TypeUserType } from './typeUserType';

export interface TypeUserInfo { 
    id?: TypeIdentifier;
    username?: TypeCommonName;
    role?: TypeUserRole;
    type?: TypeUserType;
}