/**
 * User service API
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type UserType = 'PreUniversity' | 'Enrollee' | 'School' | 'University' | 'Internal' | 'PreRegister';

export const UserType = {
    PreUniversity: 'PreUniversity' as UserType,
    Enrollee: 'Enrollee' as UserType,
    School: 'School' as UserType,
    University: 'University' as UserType,
    Internal: 'Internal' as UserType,
    PreRegister: 'PreRegister' as UserType
}

export const AllUserTypes = [ UserType.PreRegister, UserType.Enrollee, UserType.School, UserType.University, UserType.Internal, UserType.PreRegister ]