/**
 * aggregate_user
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DocumentRFInternational { 
    readonly document_name?: string;
    document_type: DocumentRFInternational.DocumentTypeEnum;
    issue_date?: string;
    issuer?: string;
    number?: string;
    series?: string;
    readonly user_id?: number;
}
export namespace DocumentRFInternational {
    export type DocumentTypeEnum = 'RFInternationalPassport';
    export const DocumentTypeEnum = {
        RfInternationalPassport: 'RFInternationalPassport' as DocumentTypeEnum
    };
}


