/**
 * aggregate_user
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentTypeEnum } from '@api/users/models/documentType'


export interface Document
{
    /**
     * Only for russian passport
     */
    code?: string | null;
    document_name?: string | null;
    document_type?: DocumentTypeEnum | null;
    issue_date?: string | null;
    issuer?: string | null;
    number?: string | null;
    series?: string | null;
    readonly user_id: number;
}

