/**
 * aggregate_user
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentForeignPassportInput } from './documentForeignPassportInput';
import { DocumentRFInput } from './documentRFInput';
import { DocumentRFInternationalInput } from './documentRFInternationalInput';
import { DocumentOtherInput } from './documentOtherInput';


/**
 * @type DocumentInput
 * @export
 */
export type DocumentInput = DocumentForeignPassportInput | DocumentOtherInput | DocumentRFInput | DocumentRFInternationalInput;

