/**
 * aggregate_user
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentBirthCertificate } from './documentBirthCertificate';
import { DocumentRF } from './documentRF';
import { DocumentForeignPassport } from './documentForeignPassport';
import { DocumentOther } from './documentOther';
import { DocumentRFInternational } from './documentRFInternational';


/**
 * @type Document
 * @export
 */
export type Document = DocumentBirthCertificate | DocumentForeignPassport | DocumentOther | DocumentRF | DocumentRFInternational;

