/**
 * aggregate_user
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocationRussiaCity } from './locationRussiaCity';


export interface LocationRussia { 
    city?: LocationRussiaCity;
    country: LocationRussia.CountryEnum;
    readonly location_type?: LocationRussia.LocationTypeEnum;
    rural?: boolean;
}
export namespace LocationRussia {
    export type CountryEnum = 'Россия';
    export const CountryEnum = {
        Russian: 'Россия' as CountryEnum
    };
    export type LocationTypeEnum = 'Russian' | 'Foreign';
    export const LocationTypeEnum = {
        Russian: 'Russian' as LocationTypeEnum,
        Foreign: 'Foreign' as LocationTypeEnum
    };
}


