/**
 * aggregate_user
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LocationOther { 
    country: string;
    location?: string;
    readonly location_type?: LocationOther.LocationTypeEnum;
    rural?: boolean;
}
export namespace LocationOther {
    export type LocationTypeEnum = 'Russian' | 'Foreign';
    export const LocationTypeEnum = {
        Russian: 'Russian' as LocationTypeEnum,
        Foreign: 'Foreign' as LocationTypeEnum
    };
}


