/**
 * aggregate_user
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoleRequestUser { 
    role: RoleRequestUser.RoleEnum;
}
export namespace RoleRequestUser {
    export type RoleEnum = 'Unconfirmed' | 'Participant' | 'Creator' | 'Admin' | 'System';
    export const RoleEnum = {
        Unconfirmed: 'Unconfirmed' as RoleEnum,
        Participant: 'Participant' as RoleEnum,
        Creator: 'Creator' as RoleEnum,
        Admin: 'Admin' as RoleEnum,
        System: 'System' as RoleEnum
    };
}


