/**
 * aggregate_user
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Location } from './location';
import { SchoolTypeEnum } from '@api/users/models/schoolType'


export interface SchoolInfo { 
    grade?: number;
    location?: Location;
    name?: string;
    number?: number;
    school_type?: SchoolTypeEnum;
    readonly user_id?: number;
}

