/**
 * aggregate_user
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Document } from './document';


export interface UserInfoSchemaPersonal { 
    date_of_birth?: string;
    document?: Document;
    first_name?: string;
    gender?: UserInfoSchemaPersonal.GenderEnum;
    middle_name?: string;
    place_of_birth?: string;
    second_name?: string;
}
export namespace UserInfoSchemaPersonal {
    export type GenderEnum = 'Male' | 'Female';
    export const GenderEnum = {
        Male: 'Male' as GenderEnum,
        Female: 'Female' as GenderEnum
    };
}


