/**
 * aggregate_user
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    readonly id?: number;
    role?: User.RoleEnum;
    type?: User.TypeEnum;
    username: string;
}
export namespace User {
    export type RoleEnum = 'Unconfirmed' | 'Participant' | 'Creator' | 'Admin' | 'System';
    export const RoleEnum = {
        Unconfirmed: 'Unconfirmed' as RoleEnum,
        Participant: 'Participant' as RoleEnum,
        Creator: 'Creator' as RoleEnum,
        Admin: 'Admin' as RoleEnum,
        System: 'System' as RoleEnum
    };
    export type TypeEnum = 'PreUniversity' | 'Enrollee' | 'School' | 'University' | 'Internal' | 'PreRegister';
    export const TypeEnum = {
        PreUniversity: 'PreUniversity' as TypeEnum,
        Enrollee: 'Enrollee' as TypeEnum,
        School: 'School' as TypeEnum,
        University: 'University' as TypeEnum,
        Internal: 'Internal' as TypeEnum,
        PreRegister: 'PreRegister' as TypeEnum
    };
}


