/**
 * aggregate_user
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudentInfo } from './studentInfo';
import { Group } from './group';
import { SchoolInfo } from './schoolInfo';
import { UserInfo } from './userInfo';


export interface UserFull { 
    groups?: Array<Group>;
    readonly id?: number;
    role: UserFull.RoleEnum;
    school_info?: SchoolInfo;
    student_info?: StudentInfo;
    type: UserFull.TypeEnum;
    user_info?: UserInfo;
    username: string;
}
export namespace UserFull {
    export type RoleEnum = 'Unconfirmed' | 'Participant' | 'Creator' | 'Admin' | 'System';
    export const RoleEnum = {
        Unconfirmed: 'Unconfirmed' as RoleEnum,
        Participant: 'Participant' as RoleEnum,
        Creator: 'Creator' as RoleEnum,
        Admin: 'Admin' as RoleEnum,
        System: 'System' as RoleEnum
    };
    export type TypeEnum = 'PreUniversity' | 'Enrollee' | 'School' | 'University' | 'Internal' | 'PreRegister';
    export const TypeEnum = {
        PreUniversity: 'PreUniversity' as TypeEnum,
        Enrollee: 'Enrollee' as TypeEnum,
        School: 'School' as TypeEnum,
        University: 'University' as TypeEnum,
        Internal: 'Internal' as TypeEnum,
        PreRegister: 'PreRegister' as TypeEnum
    };
}


