/**
 * aggregate_user
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocationInput } from './locationInput';
import { DocumentInput } from './documentInput';
import { UserLimitationsInput } from './userLimitationsInput';
import { GenderEnum } from '@api/users/models/gender'


export interface UserInfoRestrictedInput { 
    document?: DocumentInput;
    dwelling?: LocationInput;
    gender?: GenderEnum;
    limitations?: UserLimitationsInput;
    phone?: string;
    place_of_birth?: string;
}

