/**
 * aggregate_user
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserLimitations } from './userLimitations'
import { Document } from './document'
import { Location } from './location'
import { GenderEnum } from '@api/users/models/gender'


export interface UserInfo
{
    date_of_birth?: string | null;
    document?: Document | null;
    dwelling?: Location | null;
    email?: string | null;
    first_name?: string | null;
    gender?: GenderEnum | null;
    limitations?: UserLimitations | null;
    middle_name?: string | null;
    phone?: string | null;
    place_of_birth?: string | null;
    second_name?: string | null;
    readonly user_id: number;
}


