/**
 * aggregate_messages
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Message { 
    /**
     * null if sent by the participant
     */
    employee?: number;
    message: string;
    readonly message_id?: number;
    post_time?: string;
}

