/**
 * Tasks service API
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MultipleTaskInfoAnswers } from './multipleTaskInfoAnswers';

/**
 * Request to get info of task with multiple choice
 */
export interface MultipleTaskInfo { 
    taskId: number;
    numOfTask: number;
    imageOfTask: Blob;
    answers: Array<MultipleTaskInfoAnswers>;
}