/**
 * Tasks service API
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Request to get info of task with range
 */
export interface RangeTaskInfo { 
    taskId: number;
    numOfTask: number;
    imageOfTask: Blob;
    startValue: number;
    endValue: number;
}