/**
 * Tasks service API
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StagesInOlympiadStagesList } from './stagesInOlympiadStagesList';

/**
 * Request to get stages in olympiad
 */
export interface StagesInOlympiad { 
    stagesList?: Array<StagesInOlympiadStagesList>;
}