/**
 * aggregate_news
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NewsInfo { 
    category?: string;
    grade?: number;
    readonly id?: number;
    post_time?: string;
    posted?: boolean;
    related_contest?: number | null;
    title: string;
}

