/**
 * Tasks service API
 * API description in Markdown.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to creation contest
 */
export interface ContestInfoUpdate { 
    location?: string;
    start_time?: string;
    end_time?: string;
    description?: string;
    rules?: string;
    winning_condition?: string;
    laureate_condition?: string;
    certificate_template?: string;
    visibility?: boolean;
    composite_type?: ContestInfoUpdate.CompositeTypeEnum;
    olympiad_type?: ContestInfoUpdate.OlympiadTypeEnum;
    subject?: ContestInfoUpdate.SubjectEnum;
    target_class?: Array<ContestInfoUpdate.TargetClassEnum>;
}
export namespace ContestInfoUpdate {
    export type CompositeTypeEnum = 'Simple' | 'Composite';
    export const CompositeTypeEnum = {
        Simple: 'Simple' as CompositeTypeEnum,
        Composite: 'Composite' as CompositeTypeEnum
    };
    export type OlympiadTypeEnum = 'Rosatom' | 'Kurchatov';
    export const OlympiadTypeEnum = {
        Rosatom: 'Rosatom' as OlympiadTypeEnum,
        Kurchatov: 'Kurchatov' as OlympiadTypeEnum
    };
    export type SubjectEnum = 'Math' | 'Physics' | 'Informatics';
    export const SubjectEnum = {
        Math: 'Math' as SubjectEnum,
        Physics: 'Physics' as SubjectEnum,
        Informatics: 'Informatics' as SubjectEnum
    };
    export type TargetClassEnum = '5' | '6' | '7' | '8' | '9' | '10' | '11' | 'student';
    export const TargetClassEnum = {
        _5: '5' as TargetClassEnum,
        _6: '6' as TargetClassEnum,
        _7: '7' as TargetClassEnum,
        _8: '8' as TargetClassEnum,
        _9: '9' as TargetClassEnum,
        _10: '10' as TargetClassEnum,
        _11: '11' as TargetClassEnum,
        Student: 'student' as TargetClassEnum
    };
}


