/**
 * Tasks service API
 * API description in Markdown.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateMultipleTaskAnswers } from './createMultipleTaskAnswers';


/**
 * Request to creation task with multiple choice
 */
export interface CreateMultipleTask { 
    num_of_task: number;
    image_of_task: Blob;
    answers: Array<CreateMultipleTaskAnswers>;
}

