/**
 * Tasks service API
 * API description in Markdown.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to get info of task with range
 */
export interface RangeTaskInfo { 
    task_id: number;
    num_of_task: number;
    image_of_task: Blob;
    start_value: number;
    end_value: number;
}

