/**
 * Tasks service API
 * API description in Markdown.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UsersInContestUserList } from './usersInContestUserList';


/**
 * Request to get users in contest
 */
export interface UsersInContest { 
    user_list?: Array<UsersInContestUserList>;
}

