/**
 * aggregate_user
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DocumentOtherInput { 
    document_name?: string;
    document_type: DocumentOtherInput.DocumentTypeEnum;
    issue_date?: string;
    issuer?: string;
    number?: string;
    series?: string;
}
export namespace DocumentOtherInput {
    export type DocumentTypeEnum = 'OtherDocument';
    export const DocumentTypeEnum = {
        OtherDocument: 'OtherDocument' as DocumentTypeEnum
    };
}


