/**
 * User service API
 * API description in Markdown.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypeRegistrationStudentInfo } from './typeRegistrationStudentInfo';
import { TypeRegistrationCredentials } from './typeRegistrationCredentials';
import { RequestRegistrationSchool } from './requestRegistrationSchool';
import { RequestRegistrationUniversity } from './requestRegistrationUniversity';
import { TypeRegistrationPersonalInfo } from './typeRegistrationPersonalInfo';
import { TypePreregisterInfo } from './typePreregisterInfo';
import { TypeUserTypeUniversity } from './typeUserTypeUniversity';


/**
 * @type RequestRegistration
 * @export
 */
export type RequestRegistration = RequestRegistrationSchool | RequestRegistrationUniversity;

