/**
 * User service API
 * API description in Markdown.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypeRegistrationCredentials } from './typeRegistrationCredentials';
import { TypeRegistrationPersonalInfo } from './typeRegistrationPersonalInfo';
import { TypePreregisterInfo } from './typePreregisterInfo';
import { TypeUserTypeSchool } from './typeUserTypeSchool';


export interface RequestRegistrationSchool { 
    auth_info: TypeRegistrationCredentials;
    personal_info: TypeRegistrationPersonalInfo;
    register_type: TypeUserTypeSchool;
    register_confirm?: TypePreregisterInfo;
}

