/**
 * User service API
 * API description in Markdown.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypeUserInfo } from './typeUserInfo';


export interface ResponseUserByGroup { 
    users: Array<TypeUserInfo>;
}

