/**
 * aggregate_user
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocationInput } from './locationInput';


export interface SchoolInfoInput { 
    grade?: number;
    location?: LocationInput;
    name?: string;
    number?: number;
    school_type?: SchoolInfoInput.SchoolTypeEnum;
}
export namespace SchoolInfoInput {
    export type SchoolTypeEnum = 'School' | 'Lyceum' | 'Gymnasium' | 'EducationCenter' | 'NightSchool' | 'Technical' | 'External' | 'Collage' | 'ProfTech' | 'University' | 'Correctional' | 'Other';
    export const SchoolTypeEnum = {
        School: 'School' as SchoolTypeEnum,
        Lyceum: 'Lyceum' as SchoolTypeEnum,
        Gymnasium: 'Gymnasium' as SchoolTypeEnum,
        EducationCenter: 'EducationCenter' as SchoolTypeEnum,
        NightSchool: 'NightSchool' as SchoolTypeEnum,
        Technical: 'Technical' as SchoolTypeEnum,
        External: 'External' as SchoolTypeEnum,
        Collage: 'Collage' as SchoolTypeEnum,
        ProfTech: 'ProfTech' as SchoolTypeEnum,
        University: 'University' as SchoolTypeEnum,
        Correctional: 'Correctional' as SchoolTypeEnum,
        Other: 'Other' as SchoolTypeEnum
    };
}


