/**
 * User service API
 * API description in Markdown.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TypeStudentInfo { 
    phone_number?: string;
    university?: string;
    admission_year?: string;
    university_country?: string;
    citizenship?: string;
    region?: string;
    city?: string;
}

