/**
 * aggregate_user
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocationInput } from './locationInput';
import { DocumentInput } from './documentInput';
import { UserLimitationsInput } from './userLimitationsInput';


export interface UserInfoInput { 
    date_of_birth?: string;
    document?: DocumentInput;
    dwelling?: LocationInput;
    email?: string;
    first_name?: string;
    gender?: UserInfoInput.GenderEnum;
    limitations?: UserLimitationsInput;
    middle_name?: string;
    place_of_birth?: string;
    second_name?: string;
}
export namespace UserInfoInput {
    export type GenderEnum = 'Male' | 'Female';
    export const GenderEnum = {
        Male: 'Male' as GenderEnum,
        Female: 'Female' as GenderEnum
    };
}


